import Head from 'next/head'

import { Button, I18n } from '@ecommerce/ui'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button type="button">
          <I18n id="global.addToCart" />
        </Button>
      </main>
    </>
  )
}

export default Home
